/**
 * Claude via Anthropic's own API, authenticated with an API KEY. (v5.34.54)
 *
 * ── Why this exists when anthropic-vertex already does ──────────────────────
 *
 * It is the only way a CLIENT can pay for their own Claude work.
 *
 * `anthropic-vertex` authenticates with GCP service-account credentials
 * (Application Default Credentials). There is nowhere to put a client's
 * credential in that flow — a client who wants their strategy deck generated on
 * their own Anthropic account supplies an API key, and ADC cannot consume one.
 *
 * Migration 031 allows `anthropic-api` as a BYOK provider, and until this
 * adapter existed that was a promise the router could not keep — the same fault
 * the migration explicitly excludes both Vertex providers for, committed one
 * constraint line later. This closes it.
 *
 * ── When each is used ───────────────────────────────────────────────────────
 *
 *   anthropic-vertex — the firm's own Claude work. Enterprise terms, no key to
 *                      manage, no-training contractually.
 *   anthropic-api    — a client who brought their own Anthropic key. The charge
 *                      lands on THEIR Anthropic bill, not the firm's.
 *
 * The platform's own key (ANTHROPIC_API_KEY) may configure this adapter too, so
 * it can serve as a fallback when Vertex model access is unavailable — but the
 * reason it was built is BYOK.
 *
 * ── freeTier ────────────────────────────────────────────────────────────────
 *
 * false. Anthropic's API has no free tier: a key either has credit or it does
 * not, and there is no "we may train on this" tier to guard against. That is a
 * materially different situation from Google AI Studio, where a free key is
 * indistinguishable from a billed one at save time and the content may be used
 * for product improvement — which is why BYOK for Gemini needs an attestation
 * and this does not.
 */
import { normalizeFinishReason } from "../types.js";
import type { GenerateRequest, ProviderAdapter } from "../types.js";
import { estimateCost, textOf } from "../types.js";

/** Same ceiling as every other provider call — see anthropicVertex.ts. */
const PROVIDER_TIMEOUT_MS = 120_000;

/**
 * Pinned because Anthropic requires it and an unpinned request is a silent
 * behaviour change the day they ship a new default.
 */
const API_VERSION = "2023-06-01";

export interface AnthropicApiOptions {
  apiKey: string | undefined;
  model?: string;
  /** Register under a custom name — BYOK builds one adapter per tenant. */
  name?: string;
  fetchImpl?: typeof fetch;
  baseUrl?: string;
}

export function makeAnthropicApiAdapter(opts: AnthropicApiOptions): ProviderAdapter {
  // Matches anthropicVertex's default so a client's deck is generated by the
  // same model the firm's would be. Priced in PRICE_TABLE under this id.
  const model = opts.model ?? "claude-sonnet-5";
  const fetchImpl = opts.fetchImpl ?? fetch;
  const baseUrl = opts.baseUrl ?? "https://api.anthropic.com";

  return {
    name: opts.name ?? "anthropic-api",
    model,
    freeTier: false,
    isConfigured: () => Boolean(opts.apiKey),

    async generate(req: GenerateRequest) {
      let system = req.messages.filter((m) => m.role === "system").map((m) => textOf(m.content)).join("\n");
      if (req.jsonSchema) {
        system +=
          `\n\nRespond ONLY with a single JSON object valid against this JSON Schema, ` +
          `no markdown fences, no commentary:\n${JSON.stringify(req.jsonSchema)}`;
      }
      const messages = req.messages
        .filter((m) => m.role !== "system")
        .map((m) => ({ role: m.role, content: m.content }));

      const body = {
        model,                                   // on this API the model is a BODY field,
        max_tokens: req.maxTokens ?? 4096,       // unlike Vertex where it is in the URL
        temperature: req.temperature ?? 0.7,
        ...(system ? { system } : {}),
        messages,
      };

      const res = await fetchImpl(`${baseUrl}/v1/messages`, {
        method: "POST",
        signal: AbortSignal.timeout(PROVIDER_TIMEOUT_MS),
        headers: {
          "content-type": "application/json",
          "x-api-key": opts.apiKey ?? "",
          "anthropic-version": API_VERSION,
        },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        const detail = await res.text().catch(() => "");
        /*
         * The status is preserved in the message because the gateway's retry
         * logic reads it, and because a client's key failing looks very
         * different from ours failing: 401 means their key is wrong or revoked
         * and their engagement should fall back to the platform credential
         * rather than stop, while 529 is Anthropic being busy and worth
         * retrying. The key itself is never in this string.
         */
        throw new Error(`anthropic-api ${res.status}: ${detail.slice(0, 300)}`);
      }

      const data = (await res.json()) as {
        content?: { type: string; text?: string }[];
        usage?: { input_tokens?: number; output_tokens?: number };
        stop_reason?: string;
      };
      const text = (data.content ?? [])
        .filter((b) => b.type === "text")
        .map((b) => b.text ?? "")
        .join("");
      const tokensIn = data.usage?.input_tokens ?? 0;
      const tokensOut = data.usage?.output_tokens ?? 0;

      let json: unknown;
      if (req.jsonSchema) {
        const cleaned = text.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
        try {
          json = JSON.parse(cleaned);
        } catch {
          throw new Error("anthropic-api: response was not valid JSON for requested schema");
        }
      }

      return {
        finishReason: normalizeFinishReason(data.stop_reason),
        text,
        json,
        model,
        usage: { tokensIn, tokensOut, costEstUsd: estimateCost(model, tokensIn, tokensOut) },
      };
    },
  };
}
