-- =============================================================================
-- 023 — A transcript that can answer "why is this dimension a 2.4?"
--
-- v5.32.66. Migration 017 made the transcript a real record: what was said, by
-- whom, in which round. It answered "can we prove what was actually said?"
--
-- It does not answer the question a client actually asks, which is never "what
-- was said" but "why is D6 a 2.4". Today that is answerable only by reading the
-- whole conversation and inferring backwards. The scores live in the engagement
-- record, the words live here, and nothing joins them — so the reasoning behind
-- a number in a board deck is reconstructed from memory by whoever is in the
-- room.
--
-- Two columns close that.
--
--   findings     — the per-dimension observations the agent recorded DURING the
--                  interview. These already exist and already flow into
--                  Synthesis and the client document; what has never existed is
--                  a copy sitting next to the conversation that produced them.
--
--   score_events — every score MOVEMENT, with the dimension, the value before
--                  and after, and the position in the conversation it happened
--                  at. This is the part nobody has ever been able to see. The
--                  interviewer model has emitted a full score block after every
--                  single turn since the beginning; the transcript stripped it
--                  out as machine formatting and nothing else kept it.
--
-- Both are journals of what happened, not derived views, so they are stored
-- rather than recomputed: the model that produced them is non-deterministic and
-- re-deriving the trajectory later would be inventing it.
--
-- NULL, not empty array, as the default. An interview completed before this
-- migration has no journal, which is a different fact from one that produced no
-- findings — and the UI says so rather than showing an empty panel that reads
-- like "nothing was found".
-- =============================================================================

ALTER TABLE interview_transcripts ADD COLUMN IF NOT EXISTS findings     jsonb;
ALTER TABLE interview_transcripts ADD COLUMN IF NOT EXISTS score_events jsonb;

-- The existing GRANT covers these; no DELETE, same as the rest of the table.
-- (See 017 for why an audit record the application can erase is not one.)
